
markdown: kramdown

permalink: /:title

name: “槑川子的胡言乱语”
title: cc
description: 我瞎说的，你千万别信
url: http://chuanheyuanyuan.github.io
feed: /atom.xml
author_info: <a href="http://chuanheyuanyuan.github.io/">chuanheyuanyuan</a>
